version: "3"

services:
  nginx:
    build: .
    restart: unless-stopped
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/usr/share/nginx/html
      - ./logs:/var/log/nginx
    ports:
      - "80:80"
